# Development compose override
# Command: docker compose up -d

# prepend with x- for docker to ignore
x-build: &build
  # `build` and `image` to only build the image once
  build:
    context: .
    target: base
  image: "saturn:${SATURN_TAG:-1}"
  volumes:
    - .:/${APP_PATH:-app}
    - node_modules:/${APP_PATH:-app}/node_modules
    - bundle:/usr/local/bundle
x-interactive: &interactive
  # allow interactive connection
  tty: true
  stdin_open: true
x-rails-env: &rails_env
  RAILS_ENV: development
x-shared: &shared
  <<: [ *build, *interactive ]
  environment:
    <<: *rails_env
    DB_HOST: db
    CLAUDE_CONFIG_DIR: "/root/.claude"

services:
  db:
    image: postgres:17.2-alpine
    volumes:
      - saturn-database:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - ${SATURN_DB_PORT:-5432}:5432
  web:
    <<: *shared
    command: rails s -p 3000 -b 0.0.0.0
    depends_on:
      - db
    ports:
      - ${SATURN_RAILS_PORT:-3000}:3000

volumes:
  bundle:
  node_modules:
  saturn-database:
